/**
 * @module memory
 * BarTalk v8 — 3-Level Memory System
 *
 * Implements conversation memory management inspired by TMwEngine:
 * - **Level 1 (Full):** Latest N messages with complete text
 * - **Level 2 (Condensed):** Middle-aged messages with per-turn summaries
 * - **Level 3 (Summary):** Oldest messages compressed into a single summary block
 *
 * Also provides:
 * - Automatic summarization triggered every SUMMARY_TRIGGER messages
 * - Cumulative token tracking
 * - User-configurable memory parameters (fullDetailCount, condensedCount, etc.)
 * - Conversation export in plain text and Markdown formats
 * - Full conversation summary generation via AI
 */

import type { Message } from '../types/conversation';
import { callProxy } from './proxy';
import { getAPIKey, getModel } from './storage';
import { DEFAULT_MODELS } from './constants';

// ── Configurazione memoria ──────────────────────────────────────────

// ── Defaults ────────────────────────────────────────────────────────
const DEFAULT_MEMORY_CONFIG = {
  fullDetailCount: 20,
  condensedCount: 20,
  summaryThreshold: 40,
  summaryTrigger: 20,
  maxContextTokens: 6000,
  condensedMaxChars: 120,
  summaryMaxChars: 800,
};

/** Configuration shape for the 3-level memory system, controlling window sizes and thresholds. */
export type MemoryConfigType = typeof DEFAULT_MEMORY_CONFIG;

const MEMORY_SETTINGS_KEY = 'bartalk_memory_config';

/**
 * Loads memory configuration from localStorage, falling back to defaults.
 * @returns The merged memory config (user overrides + defaults)
 */
export function loadMemoryConfig(): MemoryConfigType {
  try {
    const saved = localStorage.getItem(MEMORY_SETTINGS_KEY);
    if (saved) return { ...DEFAULT_MEMORY_CONFIG, ...JSON.parse(saved) };
  } catch { /* ignore */ }
  return { ...DEFAULT_MEMORY_CONFIG };
}

/**
 * Persists memory configuration overrides to localStorage.
 * @param config - Partial config to merge with current settings
 */
export function saveMemoryConfig(config: Partial<MemoryConfigType>): void {
  try {
    const current = loadMemoryConfig();
    localStorage.setItem(MEMORY_SETTINGS_KEY, JSON.stringify({ ...current, ...config }));
  } catch { /* ignore */ }
}

/**
 * Resets memory configuration to factory defaults by removing the localStorage key.
 */
export function resetMemoryConfig(): void {
  localStorage.removeItem(MEMORY_SETTINGS_KEY);
}

/**
 * Runtime getter for current memory configuration (always reads fresh from localStorage).
 * @returns The current memory config
 */
export function getMemoryConfig(): MemoryConfigType {
  return loadMemoryConfig();
}

/** Static default memory configuration, exported for backward compatibility. */
export const MEMORY_CONFIG = DEFAULT_MEMORY_CONFIG;

// ── Tipi ─────────────────────────────────────────────────────────────

/**
 * Represents the 3-level memory structure assembled for a conversation.
 * Used to build context-aware API messages with token-efficient history.
 */
export interface MemoryBlock {
  /** Cumulative summary of oldest messages (Level 3) */
  summary: string;
  /** Condensed messages (Level 2): one-line summaries per turn */
  condensed: { role: string; content: string }[];
  /** Full recent messages (Level 1): complete text */
  full: { role: string; content: string }[];
  /** Memory statistics for diagnostics and UI display */
  stats: {
    totalMessages: number;
    level1Count: number;
    level2Count: number;
    level3Summarized: number;
    estimatedTokens: number;
  };
}

/**
 * A stored summary of a conversation segment, generated by AI auto-summarization.
 */
export interface ConversationSummary {
  id: string;
  conversationId: string;
  /** The summary text */
  content: string;
  /** Indices of messages covered by this summary: [startIdx, endIdx] */
  messageRange: [number, number];
  createdAt: string;
}

// ── Storage riassunti ────────────────────────────────────────────────

const SUMMARIES_KEY = 'bartalk_summaries';

/**
 * Loads all stored summaries for a conversation from localStorage.
 * @param conversationId - The conversation to load summaries for
 * @returns Array of summaries sorted by creation order
 */
export function loadSummaries(conversationId: string): ConversationSummary[] {
  try {
    const all = JSON.parse(localStorage.getItem(SUMMARIES_KEY) || '{}');
    return all[conversationId] || [];
  } catch { return []; }
}

/**
 * Persists a conversation summary to localStorage.
 * @param summary - The summary to store
 */
export function saveSummary(summary: ConversationSummary): void {
  try {
    const all = JSON.parse(localStorage.getItem(SUMMARIES_KEY) || '{}');
    if (!all[summary.conversationId]) all[summary.conversationId] = [];
    all[summary.conversationId].push(summary);
    localStorage.setItem(SUMMARIES_KEY, JSON.stringify(all));
  } catch { /* ignore */ }
}

/**
 * Deletes all stored summaries for a given conversation.
 * @param conversationId - The conversation whose summaries should be removed
 */
export function deleteSummaries(conversationId: string): void {
  try {
    const all = JSON.parse(localStorage.getItem(SUMMARIES_KEY) || '{}');
    delete all[conversationId];
    localStorage.setItem(SUMMARIES_KEY, JSON.stringify(all));
  } catch { /* ignore */ }
}

// ── Stima token (approssimativa: ~4 char = 1 token) ─────────────────

function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

// ── Condensatore: messaggio → 1 riga ────────────────────────────────

function condenseMessage(msg: Message): string {
  const cfg = getMemoryConfig();
  const name = msg.senderName || (msg.senderType === 'human' ? 'Utente' : 'Agente');
  const content = msg.content.trim();

  const firstSentence = content.split(/[.!?]\s/)[0];
  const condensed = firstSentence.length > cfg.condensedMaxChars
    ? firstSentence.substring(0, cfg.condensedMaxChars) + '...'
    : firstSentence;

  return `[${name}]: ${condensed}`;
}

// ── Builder principale: 3 livelli ────────────────────────────────────

/**
 * Builds the 3-level memory block from a conversation's message history.
 * Splits messages into full (Level 1), condensed (Level 2), and summary (Level 3) tiers.
 *
 * @param messages - Complete message history for the conversation
 * @param conversationId - Used to load existing summaries from localStorage
 * @returns A MemoryBlock with all three levels populated and token estimates
 */
export function buildMemoryBlock(
  messages: Message[],
  conversationId: string,
): MemoryBlock {
  const cfg = getMemoryConfig();
  const total = messages.length;
  const summaries = loadSummaries(conversationId);

  // Calcola il riassunto cumulativo (Livello 3)
  const cumulativeSummary = summaries.length > 0
    ? summaries.map(s => s.content).join('\n\n')
    : '';

  // Determina i confini dei 3 livelli
  const fullStart = Math.max(0, total - cfg.fullDetailCount);
  const condensedStart = Math.max(0, fullStart - cfg.condensedCount);

  // Livello 1: messaggi completi (ultimi N)
  const fullMessages = messages.slice(fullStart).map(m => ({
    role: m.senderType === 'human' ? 'user' : 'assistant',
    content: m.content,
  }));

  // Livello 2: messaggi condensati (N precedenti)
  const condensedMessages = messages.slice(condensedStart, fullStart).map(m => ({
    role: m.senderType === 'human' ? 'user' : 'assistant',
    content: condenseMessage(m),
  }));

  // Stima token
  const summaryTokens = estimateTokens(cumulativeSummary);
  const condensedTokens = condensedMessages.reduce((acc, m) => acc + estimateTokens(m.content), 0);
  const fullTokens = fullMessages.reduce((acc, m) => acc + estimateTokens(m.content), 0);

  return {
    summary: cumulativeSummary,
    condensed: condensedMessages,
    full: fullMessages,
    stats: {
      totalMessages: total,
      level1Count: fullMessages.length,
      level2Count: condensedMessages.length,
      level3Summarized: condensedStart, // quanti messaggi sono coperti dal riassunto
      estimatedTokens: summaryTokens + condensedTokens + fullTokens,
    },
  };
}

// ── Assembla messaggi API con i 3 livelli ────────────────────────────

/**
 * Assembles API-ready messages incorporating all 3 memory levels plus the current user message.
 * Enforces maxContextTokens by trimming oldest Level 1 messages when needed.
 *
 * @param userMessage - The current user input to append
 * @param messages - Complete conversation message history
 * @param conversationId - Used to load summaries for Level 3
 * @returns Array of role/content pairs ready for the AI provider API
 */
export function buildMemoryMessages(
  userMessage: string,
  messages: Message[],
  conversationId: string,
): { role: string; content: string }[] {
  const cfg = getMemoryConfig();
  const block = buildMemoryBlock(messages, conversationId);
  const apiMessages: { role: string; content: string }[] = [];

  // Livello 3: Riassunto cumulativo come primo messaggio di contesto
  if (block.summary) {
    // Tronca riassunto se troppo lungo
    const summaryText = block.summary.length > cfg.summaryMaxChars
      ? block.summary.substring(0, cfg.summaryMaxChars) + '...[troncato]'
      : block.summary;
    apiMessages.push({
      role: 'user',
      content: `[RIASSUNTO CONVERSAZIONE PRECEDENTE]\n${summaryText}`,
    });
    apiMessages.push({
      role: 'assistant',
      content: 'Ho letto il riassunto della conversazione precedente. Procedo con il contesto aggiornato.',
    });
  }

  // Livello 2: Messaggi condensati
  if (block.condensed.length > 0) {
    const condensedBlock = block.condensed.map(m => m.content).join('\n');
    apiMessages.push({
      role: 'user',
      content: `[CONTESTO PRECEDENTE - Sintesi]\n${condensedBlock}`,
    });
    apiMessages.push({
      role: 'assistant',
      content: 'Contesto ricevuto. Proseguo la discussione.',
    });
  }

  // Livello 1: Messaggi completi
  for (const msg of block.full) {
    apiMessages.push(msg);
  }

  // Messaggio utente corrente
  apiMessages.push({ role: 'user', content: userMessage });

  // ── TOKEN ENFORCEMENT ──────────────────────────────────────────────
  // Se il contesto supera maxContextTokens, rimuovi messaggi L1 più vecchi
  let totalTokens = apiMessages.reduce((acc, m) => acc + estimateTokens(m.content), 0);
  const maxTokens = cfg.maxContextTokens;

  if (totalTokens > maxTokens) {
    // Identifica l'indice dove iniziano i messaggi L1 (dopo L3+L2 headers)
    const l1StartIdx = block.summary ? 2 : 0;
    const l1StartWithL2 = l1StartIdx + (block.condensed.length > 0 ? 2 : 0);

    // Rimuovi messaggi L1 più vecchi finché non rientro nel limite
    while (totalTokens > maxTokens && apiMessages.length > l1StartWithL2 + 2) {
      // Rimuovi il messaggio più vecchio di L1 (non toccare L3, L2, e l'ultimo user)
      const removed = apiMessages.splice(l1StartWithL2, 1);
      if (removed.length > 0) {
        totalTokens -= estimateTokens(removed[0].content);
      } else {
        break;
      }
    }
  }

  return apiMessages;
}

// ── Controlla se serve un riassunto automatico ───────────────────────

/**
 * Checks whether an automatic summary should be generated based on unsummarized message count.
 *
 * @param messages - Current conversation messages
 * @param conversationId - The conversation to check
 * @returns True if the number of unsummarized messages exceeds the trigger threshold
 */
export function shouldTriggerSummary(
  messages: Message[],
  conversationId: string,
): boolean {
  const cfg = getMemoryConfig();
  const summaries = loadSummaries(conversationId);
  const lastSummarizedIdx = summaries.length > 0
    ? summaries[summaries.length - 1].messageRange[1]
    : 0;

  const unsummarized = messages.length - lastSummarizedIdx;
  return unsummarized >= cfg.summaryTrigger;
}

// ── Genera riassunto automatico via AI ───────────────────────────────

/**
 * Generates an AI-powered summary for unsummarized messages in a conversation.
 * Uses the first available API key from openai/anthropic/gemini/groq.
 *
 * @param messages - Complete conversation messages
 * @param conversationId - The conversation ID for summary storage
 * @returns The generated summary, or null on failure
 */
export async function generateAutoSummary(
  messages: Message[],
  conversationId: string,
): Promise<ConversationSummary | null> {
  const summaries = loadSummaries(conversationId);
  const lastSummarizedIdx = summaries.length > 0
    ? summaries[summaries.length - 1].messageRange[1]
    : 0;

  // Messaggi da riassumere: dall'ultimo riassunto fino a N messaggi fa (L1 range)
  const cfg = getMemoryConfig();
  const endIdx = Math.max(lastSummarizedIdx, messages.length - cfg.fullDetailCount);
  if (endIdx <= lastSummarizedIdx) return null;

  const toSummarize = messages.slice(lastSummarizedIdx, endIdx);
  if (toSummarize.length < 5) return null;

  // Trova una API key disponibile
  const providers = ['openai', 'anthropic', 'gemini', 'groq'] as const;
  let apiKey = '';
  let provider: typeof providers[number] = 'openai';
  for (const p of providers) {
    const key = getAPIKey(p);
    if (key) { apiKey = key; provider = p; break; }
  }
  if (!apiKey) return null;

  const model = getModel(provider) || DEFAULT_MODELS[provider];

  // Prepara il testo da riassumere
  const text = toSummarize.map(m => {
    const name = m.senderName || (m.senderType === 'human' ? 'Utente' : 'Agente');
    return `${name}: ${m.content.substring(0, 300)}`;
  }).join('\n\n');

  const systemPrompt = `Sei un assistente che crea riassunti concisi e informativi di conversazioni multi-agente.
Regole:
1. Riassumi in massimo 200 parole
2. Cattura: argomento principale, posizioni di ogni partecipante, punti di accordo/disaccordo, conclusioni raggiunte
3. Usa formato: "[Riassunto messaggi ${lastSummarizedIdx + 1}-${endIdx}] ..."
4. Mantieni i nomi degli agenti
5. Rispondi SOLO con il riassunto, nessun commento aggiuntivo`;

  try {
    const result = await callProxy({
      provider,
      model,
      messages: [{ role: 'user', content: `Riassumi questa conversazione:\n\n${text}` }],
      systemPrompt,
      temperature: 0.3,
      maxTokens: 400,
      apiKey,
    });

    if (result.error || !result.content) return null;

    const summary: ConversationSummary = {
      id: crypto.randomUUID(),
      conversationId,
      content: result.content.trim(),
      messageRange: [lastSummarizedIdx, endIdx],
      createdAt: new Date().toISOString(),
    };

    saveSummary(summary);
    return summary;
  } catch {
    return null;
  }
}

// ── Genera riassunto completo della conversazione (per utente) ───────

/**
 * Generates a comprehensive user-facing summary of an entire conversation.
 * Includes topic, participant positions, discussion development, and key insights.
 *
 * @param messages - Complete conversation messages (min 3 required)
 * @returns Markdown-formatted summary string, or null on failure
 */
export async function generateFullConversationSummary(
  messages: Message[],
): Promise<string | null> {
  if (messages.length < 3) return null;

  const providers = ['openai', 'anthropic', 'gemini', 'groq'] as const;
  let apiKey = '';
  let provider: typeof providers[number] = 'openai';
  for (const p of providers) {
    const key = getAPIKey(p);
    if (key) { apiKey = key; provider = p; break; }
  }
  if (!apiKey) return null;

  const model = getModel(provider) || DEFAULT_MODELS[provider];

  // Prepara testo (con condensamento intelligente per conversazioni lunghe)
  const textParts: string[] = [];
  for (let i = 0; i < messages.length; i++) {
    const m = messages[i];
    const name = m.senderName || (m.senderType === 'human' ? 'Utente' : 'Sistema');
    // Ultimi 10 messaggi: full; precedenti: condensati
    if (i >= messages.length - 10) {
      textParts.push(`${name}: ${m.content.substring(0, 500)}`);
    } else {
      textParts.push(`${name}: ${m.content.substring(0, 150)}...`);
    }
  }

  const text = textParts.join('\n\n');

  const systemPrompt = `Crea un riassunto completo ed esaustivo di questa conversazione multi-agente.

Struttura richiesta:
## Argomento
Breve descrizione del tema discusso.

## Partecipanti e Posizioni
Per ogni agente: nome, posizione principale, punti chiave sostenuti.

## Sviluppo della Discussione
Come si è evoluta la conversazione: punti di accordo, disaccordi, cambi di direzione.

## Conclusioni
Punti su cui si è converguto, questioni rimaste aperte.

## Punti Chiave
Elenco dei 3-5 insight più importanti emersi.

Scrivi in modo chiaro e conciso. Max 500 parole.`;

  try {
    const result = await callProxy({
      provider,
      model,
      messages: [{ role: 'user', content: `Riassumi questa conversazione:\n\n${text}` }],
      systemPrompt,
      temperature: 0.3,
      maxTokens: 1000,
      apiKey,
    });

    return result.error ? null : result.content;
  } catch {
    return null;
  }
}

// ── Export conversazione in formato testo ─────────────────────────────

/**
 * Exports a conversation as formatted plain text with timestamps and sender info.
 *
 * @param messages - Messages to export
 * @param title - Conversation title for the header
 * @returns Formatted text string ready for download
 */
export function exportConversationAsText(messages: Message[], title: string): string {
  const lines: string[] = [];
  lines.push(`# ${title}`);
  lines.push(`Esportata: ${new Date().toLocaleString('it-IT')}`);
  lines.push(`Messaggi: ${messages.length}`);
  lines.push('---\n');

  for (const m of messages) {
    const time = new Date(m.createdAt).toLocaleTimeString('it-IT', { hour: '2-digit', minute: '2-digit' });
    const name = m.senderName || (m.senderType === 'human' ? 'Utente' : 'Sistema');
    const prefix = m.senderType === 'human' ? '👤' : m.senderType === 'assistant' ? '🤖' : '⚙️';
    lines.push(`${prefix} [${time}] **${name}**${m.provider ? ` (${m.provider})` : ''}`);
    lines.push(m.content);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Exports a conversation as Markdown. Currently delegates to the text exporter.
 *
 * @param messages - Messages to export
 * @param title - Conversation title for the header
 * @returns Markdown-formatted string
 */
export function exportConversationAsMarkdown(messages: Message[], title: string): string {
  return exportConversationAsText(messages, title);
}
