/**
 * BarTalk v8 — Template Deliverable
 * Definizioni dei template per ogni tipo di deliverable.
 */

import type { DeliverableTemplate, DeliverableType } from '../types/tasks';

export const DELIVERABLE_TEMPLATES: Record<DeliverableType, DeliverableTemplate> = {
  report: {
    type: 'report',
    icon: '📄',
    label: 'Report',
    description: 'Report strutturato con sezioni, conclusioni e raccomandazioni',
    phases: ['setup', 'analysis', 'debate', 'synthesis', 'deliverable'],
    phaseInstructions: {
      setup: 'Definisci l\'obiettivo del report, i punti chiave da coprire e le fonti.',
      analysis: 'Analizza il tema da diverse prospettive. Identifica dati e fatti rilevanti.',
      debate: 'Discuti le diverse interpretazioni e prospettive. Confronta punti di vista.',
      synthesis: 'Convergi verso le conclusioni principali. Identifica raccomandazioni chiave.',
      deliverable: 'Genera il report finale strutturato con: introduzione, analisi, conclusioni, raccomandazioni.',
      completed: 'Report completato.',
    },
    outputFormat: 'markdown',
    suggestedMode: 'consultation',
  },
  analysis: {
    type: 'analysis',
    icon: '📊',
    label: 'Analisi',
    description: 'Analisi approfondita di dati, documenti o situazioni',
    phases: ['setup', 'analysis', 'debate', 'synthesis', 'deliverable'],
    phaseInstructions: {
      setup: 'Definisci il soggetto dell\'analisi e i criteri di valutazione.',
      analysis: 'Esamina i dati allegati o il tema in profondità. Identifica pattern e anomalie.',
      debate: 'Confronta diverse interpretazioni dei dati. Sfida le conclusioni preliminari.',
      synthesis: 'Sintetizza i risultati dell\'analisi. Identifica insight principali.',
      deliverable: 'Produce l\'analisi finale con: executive summary, metodologia, risultati, conclusioni.',
      completed: 'Analisi completata.',
    },
    outputFormat: 'markdown',
    suggestedMode: 'consultation',
  },
  plan: {
    type: 'plan',
    icon: '📋',
    label: 'Piano Strategico',
    description: 'Piano marketing, business plan, roadmap o pianificazione progetto',
    phases: ['setup', 'analysis', 'debate', 'synthesis', 'deliverable'],
    phaseInstructions: {
      setup: 'Definisci gli obiettivi del piano, il contesto e i vincoli.',
      analysis: 'Analizza il mercato, la concorrenza, le risorse disponibili. Identifica opportunità e rischi.',
      debate: 'Discuti le strategie possibili. Valuta pro e contro di ogni approccio.',
      synthesis: 'Seleziona la strategia migliore. Definisci milestone e KPI.',
      deliverable: 'Genera il piano completo con: obiettivi, strategia, azioni, timeline, budget, KPI.',
      completed: 'Piano completato.',
    },
    outputFormat: 'markdown',
    suggestedMode: 'consultation',
  },
  lesson: {
    type: 'lesson',
    icon: '🎓',
    label: 'Lezione',
    description: 'Lezione didattica con spiegazioni, esempi ed esercizi',
    phases: ['setup', 'analysis', 'debate', 'deliverable'],
    phaseInstructions: {
      setup: 'Definisci l\'argomento, il livello degli studenti e gli obiettivi di apprendimento.',
      analysis: 'Identifica i concetti chiave, gli esempi più efficaci e le difficoltà comuni.',
      debate: 'Discuti le diverse metodologie didattiche. Scegli l\'approccio più efficace.',
      synthesis: '',
      deliverable: 'Genera la lezione completa con: introduzione, spiegazione teorica, esempi pratici, esercizi, riepilogo.',
      completed: 'Lezione completata.',
    },
    outputFormat: 'markdown',
    suggestedMode: 'consultation',
  },
  creative: {
    type: 'creative',
    icon: '✍️',
    label: 'Testo Creativo',
    description: 'Racconto, articolo, testo pubblicitario, contenuti creativi',
    phases: ['setup', 'debate', 'synthesis', 'deliverable'],
    phaseInstructions: {
      setup: 'Definisci il genere, il tono, il pubblico target e il messaggio chiave.',
      analysis: '',
      debate: 'Esplora diverse direzioni creative. Proponi angoli narrativi alternativi.',
      synthesis: 'Seleziona la direzione creativa migliore. Definisci struttura e tono definitivi.',
      deliverable: 'Scrivi il testo creativo finale, curato nei dettagli stilistici e narrativi.',
      completed: 'Testo completato.',
    },
    outputFormat: 'markdown',
    suggestedMode: 'consultation',
  },
  code: {
    type: 'code',
    icon: '💻',
    label: 'Codice',
    description: 'Script, componente, algoritmo o soluzione tecnica',
    phases: ['setup', 'analysis', 'debate', 'deliverable'],
    phaseInstructions: {
      setup: 'Definisci i requisiti tecnici, il linguaggio, le dipendenze e i vincoli.',
      analysis: 'Analizza l\'architettura necessaria. Identifica componenti e pattern da usare.',
      debate: 'Discuti approcci alternativi. Valuta trade-off tra performance, leggibilità e manutenibilità.',
      synthesis: '',
      deliverable: 'Genera il codice completo, commentato, con gestione errori e best practice.',
      completed: 'Codice completato.',
    },
    outputFormat: 'text',
    suggestedMode: 'consultation',
  },
  brainstorm: {
    type: 'brainstorm',
    icon: '💡',
    label: 'Brainstorming',
    description: 'Sessione di brainstorming strutturata con selezione idee',
    phases: ['setup', 'debate', 'synthesis', 'deliverable'],
    phaseInstructions: {
      setup: 'Definisci il problema o l\'opportunità. Nessun giudizio in questa fase.',
      analysis: '',
      debate: 'GENERA IDEE LIBERAMENTE. Ogni agente propone almeno 3 idee originali. Nessuna critica.',
      synthesis: 'Valuta e seleziona le idee migliori. Combina idee complementari.',
      deliverable: 'Produce il documento finale: lista idee selezionate, analisi fattibilità, prossimi passi.',
      completed: 'Brainstorming completato.',
    },
    outputFormat: 'markdown',
    suggestedMode: 'consultation',
  },
  review: {
    type: 'review',
    icon: '🔍',
    label: 'Revisione',
    description: 'Revisione e miglioramento di un documento o testo esistente',
    phases: ['setup', 'analysis', 'debate', 'deliverable'],
    phaseInstructions: {
      setup: 'Carica il documento da revisionare. Definisci i criteri di revisione.',
      analysis: 'Analizza il documento: struttura, contenuto, stile, accuratezza, completezza.',
      debate: 'Ciascun agente fornisce feedback da prospettive diverse. Identifica punti di forza e debolezze.',
      synthesis: '',
      deliverable: 'Produce la versione migliorata del documento con le modifiche suggerite applicate.',
      completed: 'Revisione completata.',
    },
    outputFormat: 'markdown',
    suggestedMode: 'consultation',
  },
  custom: {
    type: 'custom',
    icon: '⚙️',
    label: 'Personalizzato',
    description: 'Obiettivo personalizzato con fasi configurabili',
    phases: ['setup', 'analysis', 'debate', 'synthesis', 'deliverable'],
    phaseInstructions: {
      setup: 'Definisci l\'obiettivo e i criteri di successo.',
      analysis: 'Analizza il tema in profondità.',
      debate: 'Discuti approcci e prospettive diverse.',
      synthesis: 'Convergi verso la soluzione migliore.',
      deliverable: 'Genera il deliverable finale.',
      completed: 'Obiettivo completato.',
    },
    outputFormat: 'markdown',
    suggestedMode: 'consultation',
  },
};

export const PHASE_LABELS: Record<string, { icon: string; label: string }> = {
  setup: { icon: '🎯', label: 'Setup' },
  analysis: { icon: '🔎', label: 'Analisi' },
  debate: { icon: '💬', label: 'Dibattito' },
  synthesis: { icon: '🔄', label: 'Sintesi' },
  deliverable: { icon: '📦', label: 'Deliverable' },
  completed: { icon: '✅', label: 'Completato' },
};
